### ISSUE TITLE
Image - background of the dialog periodically disappears when using animated images

### ISSUE THREAD

**Issue by EpicNet** [twig/dcxdll#69] opened 2021-11-20 22:00 UTC
I am using "**mIRC v7.67**" + "**DCX dll v3.1-git469**" in system "Windows 8.1 x64".

When using an animated image, if first close the dialog and then quickly open it again, then its background periodically disappears and acquires the effect of transparency (as if there is no colored background) and everything under the dialog box is visible. Can work around this problem by adding a timer to the command: "**/timer 1 0 /xdid -i $dname 1 +abh %image_path**".

So, either this issue needs to be fixed in code, or in the reference documentation, in a note, indicate that the command that will use the animated image needs to be used with a timer to delay the animation before the background is drawn.

Would like to see a fix for this problem. Thanks.

---

![image](https://i.ibb.co/tDy1dZd/image-nobg.png)

Here is a test piece of script to reproduce this the problem. To run the script click on "**F5**" or enter the command "**/image_test**":

```
alias F5 { image_test }
alias image_test {
  if ($dialog(image_test)) .dialog -x image_test | else { .dialog -m image_test image_test }
}
dialog image_test {
  title "Image test"
  icon $mircexe,0
  option pixels
  size -1 -1 450 300
}
on *:DIALOG:image_test:init:0:{
  .dcx Mark $dname image_test_work
  .xdialog -b $dname +ty
  .xdialog -g $dname +b $rgb(20,20,27)
  .xdialog -c $dname 1 image 30 25 390 250 notheme 
  .xdid -x $dname 1 +b
  .xdid -S $dname 1 1
  .xdid -C $dname 1 +b $rgb(40,40,47)
  var %image_path image\gif\file1.gif
  if ($exists(%image_path)) .xdid -i $dname 1 +abh %image_path
}
alias image_test_work {}
```

**Comment by OokEek** [comment] 2021-11-22 18:38
Unable to reproduce.

**Comment by EpicNet** [comment] 2021-11-22 20:45
**OokEek**, I made a short video to demonstrate the bug:  🎥 [Video](http://epicnet.ru/video/DCX_3.1.469_Image_Bug.webm)

The color background of the dialog box disappears (it becomes transparent) around the control. This can catch when you quickly close and open the dialog with the "**F5**" key. Probably some of the configured parameters are do not have time to update to display in the dialog due permanent to the animation being played.

**Comment by OokEek** [comment] 2021-11-26 22:02
Still unable to reproduce, i can only assume this has been fixed in the current build.
closing for now, reopen if this persists.

**Closed by OokEek** 2021-11-26 22:02 UTC
