### ISSUE TITLE
ComboEx

### ISSUE THREAD

**Issue by d3Vilb4T** [twig/dcxdll#23] opened 2017-11-09 18:35 UTC
$xdid(dialog,id,0).text won't return line 0 for dropedit and simple ComboEx style.

**Comment by OokEek** [comment] 2018-07-15 13:51
This seems to have been caused by how /xdid -c set the selected text & how $xdid(dialog,id,0).text recalled it.
Fixed now...

**Closed by OokEek** 2018-07-15 13:51 UTC
